// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", false);
user_pref("app.normandy.user_id", "9916d797-d146-49bd-a28d-6b2ee7110618");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1542991563);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1542991683);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1542999568);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1542991236);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1542992787);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1542991356);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1542991923);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1542991803);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.ctrlTab.migrated", true);
user_pref("browser.ctrlTab.recentlyUsedOrder", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1528856038);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.migration.version", 74);
user_pref("browser.newtabpage.activity-stream.impressionId", "{078ff08b-5560-4c07-8374-05baf1c015c8}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1528776000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1528856067);
user_pref("browser.onboarding.notification.tour-ids-queue", "");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.state", "watermark");
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\",\"addSearchEngine\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1542998484747");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1543000309747");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1542998511055");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1543002111055");
user_pref("browser.search.countryCode", "HK");
user_pref("browser.search.region", "HK");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181116154524");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1542995706");
user_pref("browser.slowStartup.averageTime", 736);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20181116154524");
user_pref("browser.startup.homepage_override.mstone", "63.0.3");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1528856053010");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("devtools.performance.recording.interval", 1000);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "63.0.3");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "1cd058a91c9c491b8f42f1fdb7c53c04");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.lastModified", "Thu, 15 Nov 2018 09:04:34 GMT");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1542991563);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181116154524");
user_pref("extensions.lastAppVersion", "63.0.3");
user_pref("extensions.lastPlatformVersion", "63.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{d4829336-b842-49ce-b32b-077d4121be8e}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"0f3b85fc-1cd9-4196-a608-e9f1a5501add\",\"formautofill@mozilla.org\":\"1b1dd29a-c28e-4932-ae09-d4ed794b1a6a\",\"webcompat@mozilla.org\":\"552cbc3b-5946-4908-8726-1568a3e235e7\",\"fxmonitor@mozilla.org\":\"0d358baf-5cec-4809-974a-d0fa02d6e3ad\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1542993098);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1528860439);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181116154524");
user_pref("media.gmp-manager.lastCheck", 1542991425);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1542993098);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "4c6c44a6-381d-4708-b3c0-c3c3e9929903");
user_pref("services.blocklist.addons.checked", 1542916291);
user_pref("services.blocklist.gfx.checked", 1542916291);
user_pref("services.blocklist.onecrl.checked", 1542916291);
user_pref("services.blocklist.pinning.checked", 1542916291);
user_pref("services.blocklist.plugins.checked", 1542916291);
user_pref("services.settings.clock_skew_seconds", -242);
user_pref("services.settings.last_update_seconds", 1542991668);
user_pref("services.settings.main.tippytop.last_check", 1542916291);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1542993098);
user_pref("toolkit.startup.last_success", 1542995704);
user_pref("toolkit.telemetry.cachedClientID", "4749ce36-6f7f-4e6f-a490-5d4919a39089");
user_pref("toolkit.telemetry.previousBuildID", "20181116154524");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
